# Generated by Django 3.0.4 on 2020-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('mobileno', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
