# Generated by Django 3.0.4 on 2020-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sale', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=400, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('qty', models.IntegerField(default=0)),
                ('special', models.CharField(max_length=200)),
            ],
        ),
    ]
