# Generated by Django 3.0.4 on 2020-03-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0004_auto_20200328_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special',
        ),
    ]
