# Generated by Django 3.0.4 on 2020-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0008_auto_20200402_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_large',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_small',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_xtraLarge',
            field=models.IntegerField(default=0),
        ),
    ]
