# Generated by Django 3.0.4 on 2020-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0012_alllogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty_large',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty_medium',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty_small',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty_xtraLarge',
        ),
        migrations.AddField(
            model_name='cart',
            name='SIZE',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='AllLogin',
        ),
    ]
