# Generated by Django 3.0.4 on 2020-04-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0013_auto_20200405_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductINSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceAfterSale', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('Oneplus1', models.BooleanField(default=False)),
                ('Twoplus1', models.BooleanField(default=False)),
                ('Threeplus1', models.BooleanField(default=False)),
                ('one_helfSecond', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(through='onlineStyle_App.ProductINSale', to='onlineStyle_App.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productinsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineStyle_App.Product'),
        ),
        migrations.AddField(
            model_name='productinsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineStyle_App.Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ManyToManyField(through='onlineStyle_App.ProductINSale', to='onlineStyle_App.Sale'),
        ),
    ]
