# Generated by Django 3.0.4 on 2020-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0014_auto_20200409_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Oneplus1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Threeplus1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Twoplus1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='one_helfSecond',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale',
            field=models.IntegerField(choices=[(0, 'None'), (1, '1+1'), (2, '2+1'), (3, '3+1'), (4, '1+1/2')], default=0),
        ),
    ]
