# Generated by Django 3.0.4 on 2020-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0017_auto_20200409_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale',
            field=models.IntegerField(choices=[(0, 'None'), (1, '1+1'), (2, '2+1'), (3, '3+1')], default=0),
        ),
    ]
