# Generated by Django 3.0.4 on 2020-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0019_remove_productinsale_priceaftersale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale',
            field=models.IntegerField(choices=[(0, 'None'), (1, '1+1'), (2, '2+1'), (3, '1+1/2')], default=0),
        ),
    ]
