# Generated by Django 3.0.4 on 2020-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0023_remove_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartAvilable',
            field=models.IntegerField(choices=[(1, 'Avilable'), (0, 'notAvilable')], default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.IntegerField(choices=[(1, 'canceled'), (2, 'complete'), (3, 'tracking')], default=1),
        ),
    ]
