# Generated by Django 3.0.4 on 2020-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0026_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.IntegerField(choices=[(2, 'complete'), (3, 'tracking'), (0, 'None')], default=0),
        ),
    ]
