# Generated by Django 3.0.4 on 2020-04-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0027_auto_20200411_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField(default=1)),
                ('order', models.IntegerField(choices=[(0, 'None'), (3, 'tracking'), (2, 'complete')], default=0)),
                ('cart', models.ManyToManyField(to='onlineStyle_App.Cart')),
            ],
        ),
    ]
