# Generated by Django 3.0.4 on 2020-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0029_auto_20200411_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(choices=[(3, 'tracking'), (2, 'complete')], default=3),
        ),
    ]
