# Generated by Django 3.0.4 on 2020-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0031_sale_freeshipping_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FreeShipping_totalPrice', models.IntegerField(default=0)),
                ('shippingPrice', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='FreeShipping_totalPrice',
        ),
    ]
