# Generated by Django 3.0.4 on 2020-04-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0032_auto_20200412_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeShipping',
        ),
    ]
