# Generated by Django 3.0.4 on 2020-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0034_auto_20200413_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='CLUB_CARD',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0),
        ),
    ]
