# Generated by Django 3.0.4 on 2020-04-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0036_auto_20200416_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='FreeShipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
