# Generated by Django 3.0.4 on 2020-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0037_auto_20200416_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'cancle'), (2, 'tracking'), (1, 'complete')], default=2),
        ),
    ]
