# Generated by Django 3.0.4 on 2020-04-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0038_auto_20200417_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIZE', models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineStyle_App.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineStyle_App.Person')),
            ],
        ),
    ]
