# Generated by Django 3.0.4 on 2020-04-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStyle_App', '0039_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
